<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.PDF" Version="24.11.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OJTEDU.Application\OJTEDU.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\documents\" />
    <Folder Include="wwwroot\faqs\" />
    <Folder Include="wwwroot\internshipprocess\" />
    <Folder Include="wwwroot\userguides\" />
    <Folder Include="wwwroot\uploads\applications\cvFiles\" />
    <Folder Include="wwwroot\uploads\applications\testFiles\" />
    <Folder Include="wwwroot\uploads\attendancereports\files\" />
    <Folder Include="wwwroot\uploads\cvs\" />
  </ItemGroup>

</Project>
